sudo: required

services:
  - docker

before_install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker pull store/softwareag/commandcentral:10.1-server
  - docker pull store/softwareag/commandcentral:10.1-node

script:
  - docker network create ccnetwork
  - docker run --name cc -d -p 8091 --network ccnetwork store/softwareag/commandcentral:10.1-server
  - docker run --name n1 -d -P --network ccnetwork store/softwareag/commandcentral:10.1-node
  - docker build -t sergeipogrebnyak/commandcentral:10.1-server .
  - docker run --name cc -d -p 8091 --network ccnetwork sergeipogrebnyak/commandcentral:10.1-server

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push sergeipogrebnyak/commandcentral:10.1-server
    fi
